// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqalmebhMgjAsoTT288T1mknc70ZOvIk',
    appId: '1:428301984316:web:dad3d5fdb3f404b4cc9939',
    messagingSenderId: '428301984316',
    projectId: 'niigata-flower-guide',
    authDomain: 'niigata-flower-guide.firebaseapp.com',
    storageBucket: 'niigata-flower-guide.firebasestorage.app',
    measurementId: 'G-0Y3BG0DEED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqalmebhMgjAsoTT288T1mknc70ZOvIk',
    appId: '1:428301984316:android:dad3d5fdb3f404b4cc9939',
    messagingSenderId: '428301984316',
    projectId: 'niigata-flower-guide',
    storageBucket: 'niigata-flower-guide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyqalmebhMgjAsoTT288T1mknc70ZOvIk',
    appId: '1:428301984316:ios:dad3d5fdb3f404b4cc9939',
    messagingSenderId: '428301984316',
    projectId: 'niigata-flower-guide',
    storageBucket: 'niigata-flower-guide.firebasestorage.app',
    iosBundleId: 'com.example.niigataFlowerGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyqalmebhMgjAsoTT288T1mknc70ZOvIk',
    appId: '1:428301984316:ios:dad3d5fdb3f404b4cc9939',
    messagingSenderId: '428301984316',
    projectId: 'niigata-flower-guide',
    storageBucket: 'niigata-flower-guide.firebasestorage.app',
    iosBundleId: 'com.example.niigataFlowerGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyqalmebhMgjAsoTT288T1mknc70ZOvIk',
    appId: '1:428301984316:web:dad3d5fdb3f404b4cc9939',
    messagingSenderId: '428301984316',
    projectId: 'niigata-flower-guide',
    authDomain: 'niigata-flower-guide.firebaseapp.com',
    storageBucket: 'niigata-flower-guide.firebasestorage.app',
    measurementId: 'G-0Y3BG0DEED',
  );
} 